# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('posts', models.IntegerField(default=0)),
                ('page_name', models.TextField(unique=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('thumb_directory', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.TextField(null=True)),
                ('caption', models.TextField(null=True)),
                ('date_posted', models.TextField(null=True)),
                ('image_directory', models.TextField(null=True)),
                ('post_id', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.Page')),
            ],
        ),
    ]
