# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=models.TextField(unique=True)),
        ),
        migrations.AlterField(
            model_name='page',
            name='followers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='following',
            field=models.IntegerField(),
        ),
    ]
